### ISSUE TITLE
Join OSPO++ Page

### ISSUE THREAD

**Issue by clcoffey** [ospoplusplus/ospoplusplus.org#8]
Rename the Services page to Join OSPO++
This page will be nested under Community in the menu.

**Comment by clcoffey** [comment]
Hi Diren,

My changes to this page got deleted when you merged your branch.

We will need to re-create the services page layout on this page and bring back the content I had put there.

**Comment by clcoffey** [comment]
Here is a screenshot of the content I had added to this page. 
Can you make sure to add it back please.
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/78749459/195367675-a20927ea-cda7-4007-9ac4-bd31050dfb32.png">

**Comment by direnakkoc** [comment]
Hi @clcoffey,
It's done and this the link for the latest commit https://github.com/ospoplusplus/ospoplusplus.org/commit/8b1d8c04fde12bf1119c772339a12436b9fd5812
